In [1]:
#TASK 1

import numpy as np

# Create a numpy array of size 10 filled with zeros
zeros_array = np.zeros(10)

print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#TASK 2

float_array = np.arange(10, 50, dtype=float)

print(float_array)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [4]:
#TASK 3

ones_matrix = np.ones((2, 2), dtype=int)

print(ones_matrix)

[[1 1]
 [1 1]]


In [5]:
#TASK 4

ones_matrix_float = np.ones((3, 2), dtype=float)

print(ones_matrix_float)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
# TASK 5

# Suppose X is your existing numpy array
X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a new array with the same shape and type as X, filled with ones
ones_like_X = np.ones_like(X)

print(ones_like_X)

[[1 1 1]
 [1 1 1]]


In [7]:
# TASK 6

# Suppose X is your existing numpy array
X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a new array with the same shape and type as X, filled with zeros
zeros_like_X = np.zeros_like(X)

print(zeros_like_X)

[[0 0 0]
 [0 0 0]]


In [8]:
# TASK 7

fives_matrix = np.full((4, 4), 5, dtype=int)

print(fives_matrix)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [9]:
#TASK 8

X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a new array with the same shape and type as X, filled with sevens
sevens_like_X = np.full_like(X, 7)

print(sevens_like_X)

[[7 7 7]
 [7 7 7]]


In [10]:
#TASK 9

identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# TASK 10

random_array = np.random.randint(1, 11, 3)

print(random_array)

[ 7  4 10]


In [12]:
# TASK 11

random_float_matrix = np.random.rand(3, 3, 3)

print(random_float_matrix)


[[[0.69130598 0.02845573 0.23669772]
  [0.85446711 0.56002425 0.17288552]
  [0.50301483 0.64021681 0.94275377]]

 [[0.54955747 0.76864801 0.59716111]
  [0.72175798 0.96959295 0.88959275]
  [0.61967692 0.34449427 0.25637599]]

 [[0.11635411 0.88910568 0.51647929]
  [0.26185713 0.13280716 0.72538773]
  [0.44543455 0.98452403 0.120025  ]]]


In [13]:
# TASK 12
array_1_to_10 = np.arange(1, 11)

print(array_1_to_10)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
#TASK 13

# Create a numpy array with odd numbers from 1 to 10
odd_numbers_array = np.arange(1, 11, 2)

print(odd_numbers_array)


[1 3 5 7 9]


In [15]:
# TASK 14

descending_array = np.arange(10, 0, -1)

print(descending_array)


[10  9  8  7  6  5  4  3  2  1]


In [16]:
# TASK 15

matrix_3x3 = np.arange(9).reshape((3, 3))

print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# TASK 1

X = np.array(['A', 'B', 'C', 'D', 'E'])

first_element = X[0]

print(first_element)

A


In [18]:
#TASK 2
X = np.array(['A', 'B', 'C', 'D', 'E'])

last_element = X[-1]

print(last_element)

E


In [19]:
#TASK 3

X = np.array(['A', 'B', 'C', 'D', 'E'])

first_three_elements = X[:3]

print(first_three_elements)

['A' 'B' 'C']


In [20]:
# TASK 4

X = np.array(['A', 'B', 'C', 'D', 'E'])

middle_elements = X[1:-1]

print(middle_elements)

['B' 'C' 'D']


In [21]:
#TASK 5

X = np.array(['A', 'B', 'C', 'D', 'E'])

reverse_elements = X[::-1]

print(reverse_elements)

['E' 'D' 'C' 'B' 'A']


In [22]:
# TASK 6

X = np.array(['A', 'B', 'C', 'D', 'E'])

odd_position_elements = X[::2]

print(odd_position_elements)


['A' 'C' 'E']


In [23]:
# TASK 7

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

first_row_elements = X[0, :]

print(first_row_elements)

[1 2 3 4]


In [24]:
# TASK 8

import numpy as np

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

last_row_elements = X[-1, :]

print(last_row_elements)


[13 14 15 16]


In [25]:
# TASK 9

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

first_element_first_row = X[0, 0]

print(first_element_first_row)


1


In [26]:
# TASK 10

import numpy as np

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

last_element_last_row = X[-1, -1]

print(last_element_last_row)


16


In [29]:
# TASK 11

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

first_two_elements_first_two_rows = X[:2, :2]

print(first_two_elements_first_two_rows)


[[1 2]
 [5 6]]


In [30]:
# TASK 12

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Show the last two elements on the last two rows
last_two_elements_last_two_rows = X[-2:, -2:]

print(last_two_elements_last_two_rows)


[[11 12]
 [15 16]]


In [31]:
# TASK 1

X = np.array([-5, -3, 0, 10, 40])

X_float = X.astype(float)

print(X_float)

[-5. -3.  0. 10. 40.]


In [32]:
# TASK 2

X = np.array([-5, -3, 0, 10, 40])

reversed_X = X[::-1]

print(reversed_X)


[40 10  0 -3 -5]


In [33]:
# TASK 3

X = np.zeros(10)

X[4] = 1

print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [34]:
# TASK 4

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, :] = 1

print(X)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [35]:
# TASK 5

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X += 5

print(X)


[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
